global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "django"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "web:8000"

  - job_name: "node"
    static_configs:
      - targets:
          - "taskflow-pro-node-exporter:9100"